### ISSUE TITLE
Installation/make fails in empty project

### ISSUE THREAD

**Issue by krlwlfrt** [thinkbaer/node-aios#5]
I just started a new empty project and tried to install aios into it with `npm install aios`.

Make failed with the following message:

```
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:122:20)
    at Object.runInThisContext (vm.js:329:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at evalScript (internal/bootstrap/node.js:590:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```

`nan` seems to be an implicit (build) dependency?

**Comment by krlwlfrt** [comment]
It works when I install `nan` first with `npm install nan`.

**Comment by cezaryrk** [comment]
C++ Zeug wird ab version 1.0.0 nicht mehr benötigt
